### ISSUE TITLE
Blank Export Dialogue Box

### ISSUE THREAD

**Issue by AltaluneV** [emilianavt/VSeeFaceSDK#12] opened 2022-02-18 04:35 UTC
Dialogue box after selecting character in the Hierarchy list (using Unity 2019.4.16) and then VSF SDK > Export Avatar Bundle pops up blank except for the option to select "OK". Upon selecting "OK", the box closes and nothing happens. Thoughts? I've tried removing VSF SDK and then adding a fresh copy.

**Comment by emilianavt** [comment] 2022-02-18 10:56
This type of issue is usually cause by Unity being unable to correctly compile the scripts of the VSF SDK due to compiler errors, mostly caused by other assets. Please check the "Console" tab in Unity. You will most likely find some errors marked in red. Resolving those should make the SDK function correctly.

**Closed** 2022-05-11 14:42 UTC
